export const routes = {
  home: '/',
  login: '/login',
  register: '/register',
  dashboard: '/dashboard',
  services: '/services',
  serviceDetail: (id: string) => `/services/${id}`,
  events: '/events',
  profile: '/profile',
  admin: '/admin',
  adminNeighborhoods: '/admin/neighborhoods',
  adminUsers: '/admin/users',
  adminServices: '/admin/services',
  adminEvents: '/admin/events',
  adminIncidents: '/admin/incidents',
  adminAlertes: '/admin/alertes',
} as const
